import { useState } from "react";
import { Droplets, Leaf, Plus } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const progress = [{ week: "W1", weight: 76 }, { week: "W2", weight: 75.4 }, { week: "W3", weight: 74.8 }, { week: "W4", weight: 74 }];

export function DietProgressFeature() {
  const [meals, setMeals] = useState([{ time: "07:30", name: "Oats, banana & unsweetened tea", done: true }, { time: "12:30", name: "Brown rice, dhal & green salad", done: false }, { time: "19:00", name: "Grilled fish and steamed vegetables", done: false }]);
  const [water, setWater] = useState(5);
  return <div className="stack-xl"><div className="page-heading"><div><span className="eyebrow">Module 04 · IT25101696</span><h1>Diet plans & progress</h1><p>Personalized nutrition with simple daily tracking.</p></div><button className="primary"><Plus size={16}/> Create plan</button></div><div className="feature-grid equal"><section className="panel"><div className="panel-title"><div><span className="eyebrow">Published plan</span><h2>Low-sugar balanced plan</h2></div><span className="status confirmed">Active</span></div><div className="chip-row"><span className="chip active"><Leaf size={12}/> 1,850 kcal</span><span className="chip">Low added sugar</span><span className="chip">High fibre</span></div><div className="list" style={{ marginTop: 16 }}>{meals.map((meal, index) => <button className="list-item" key={meal.time} onClick={() => setMeals((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, done: !item.done } : item))}><span className="avatar">{meal.done ? "✓" : meal.time.slice(0, 2)}</span><span className="grow"><strong>{meal.time}</strong><small>{meal.name}</small></span><span className={meal.done ? "status confirmed" : "status pending"}>{meal.done ? "Completed" : "Planned"}</span></button>)}</div><div className="tip-card" style={{ marginTop: 14, padding: 14, borderRadius: 12 }}><Droplets/><div><h2>{water} of 8 glasses</h2><p>Tap to record another glass of water.</p><button className="text-button" onClick={() => setWater((value) => Math.min(8, value + 1))}>+ Add water</button></div></div></section><section className="panel"><div className="panel-title"><div><span className="eyebrow">Four-week trend</span><h2>Weight progress</h2></div><strong style={{ color: "var(--green)" }}>84% adherence</strong></div><div className="chart-box"><ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={progress}><defs><linearGradient id="dietGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#2b795d" stopOpacity={.35}/><stop offset="95%" stopColor="#2b795d" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#d7e4dc"/><XAxis dataKey="week" stroke="#687e74" fontSize={11}/><YAxis domain={[70, 78]} stroke="#687e74" fontSize={11}/><Tooltip/><Area type="monotone" dataKey="weight" stroke="#2b795d" strokeWidth={3} fill="url(#dietGradient)"/></AreaChart></ResponsiveContainer></div><div className="success-note">Goal progress: 2 kg lost toward the 5 kg target. Measurements are for demonstration only.</div></section></div></div>;
}
