package lk.sliit.nutricare.appointment;import java.math.BigDecimal;import java.time.Instant;import java.util.*;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class AppointmentService{private final SlotRepository slots;private final AppointmentRepository appointments;private final InvoiceRepository invoices;private final PaymentRepository payments;AppointmentService(SlotRepository s,AppointmentRepository a,InvoiceRepository i,PaymentRepository p){slots=s;appointments=a;invoices=i;payments=p;}
 @Transactional public Booking hold(UUID slotId,UUID patientId,String service,BigDecimal amount){AvailabilitySlot slot=slots.findForUpdate(slotId).orElseThrow(()->new IllegalArgumentException("Slot not found"));slot.hold();Appointment appointment=appointments.save(new Appointment(slot,patientId,service));Invoice invoice=invoices.save(new Invoice(appointment.getId(),amount));return new Booking(appointment,invoice,slot);}
 @Transactional public Payment pay(UUID appointmentId,BigDecimal amount,String method,String status){if(Set.of("CARD","CASH","BANK_TRANSFER","MOBILE_WALLET").stream().noneMatch(x->x.equals(method)))throw new IllegalArgumentException("Unsupported demo payment method");if(!Set.of("PAID","PENDING","PARTIALLY_PAID","FAILED","REFUNDED").contains(status))throw new IllegalArgumentException("Unsupported payment status");Appointment a=appointments.findById(appointmentId).orElseThrow();Invoice i=invoices.findByAppointmentId(appointmentId).orElseThrow();Payment p=payments.save(new Payment(i.getId(),amount,method,status));if("PAID".equals(status)||"PARTIALLY_PAID".equals(status)){AvailabilitySlot s=slots.findForUpdate(a.getSlotId()).orElseThrow();s.book();a.confirm();i.setStatus("PAID".equals(status)?"PAID":"PARTIALLY_PAID");}return p;}
 @Transactional public void cancel(UUID appointmentId){Appointment a=appointments.findById(appointmentId).orElseThrow();a.cancel();slots.findForUpdate(a.getSlotId()).ifPresent(AvailabilitySlot::release);}
 @Scheduled(fixedDelay=60000)@Transactional public void releaseExpired(){for(AvailabilitySlot s:slots.findByStatusAndHoldExpiresAtBefore("HELD",Instant.now())){appointments.findBySlotId(s.getId()).filter(a->"HELD".equals(a.getStatus())).ifPresent(Appointment::expire);s.release();}}
 public record Booking(Appointment appointment,Invoice invoice,AvailabilitySlot slot){}
}

