package lk.sliit.nutricare.appointment;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.math.BigDecimal;import java.time.*;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;
@RestController@RequestMapping("/api/v1")public class AppointmentController{private final SlotRepository slots;private final AppointmentRepository appointments;private final AppointmentService service;AppointmentController(SlotRepository s,AppointmentRepository a,AppointmentService x){slots=s;appointments=a;service=x;}
 @GetMapping("/schedules/slots")List<AvailabilitySlot>slots(@RequestParam LocalDate date){return slots.findByStartTimeBetweenOrderByStartTime(date.atStartOfDay(),date.plusDays(1).atStartOfDay());}
 @PostMapping("/appointments/hold")@PreAuthorize("hasAnyRole('PATIENT','RECEPTION_STAFF')")@ResponseStatus(HttpStatus.CREATED)AppointmentService.Booking hold(@Valid@RequestBody HoldRequest r){return service.hold(r.slotId(),r.patientId(),r.serviceType(),r.amount());}
 @PostMapping("/appointments/{id}/payments")@PreAuthorize("hasAnyRole('PATIENT','RECEPTION_STAFF','FINANCE_EXECUTIVE')")@ResponseStatus(HttpStatus.CREATED)Payment pay(@PathVariable UUID id,@Valid@RequestBody PaymentRequest r){return service.pay(id,r.amount(),r.method(),r.status());}
 @PostMapping("/appointments/{id}/cancel")@PreAuthorize("hasAnyRole('PATIENT','RECEPTION_STAFF')")void cancel(@PathVariable UUID id){service.cancel(id);}
 @GetMapping("/appointments/patient/{patientId}")@PreAuthorize("hasRole('RECEPTION_STAFF') or principal == #patientId")List<Appointment>patient(@PathVariable UUID patientId){return appointments.findByPatientId(patientId);}
 record HoldRequest(@NotNull UUID slotId,@NotNull UUID patientId,@NotBlank String serviceType,@NotNull@DecimalMin("0.00")BigDecimal amount){}record PaymentRequest(@NotNull@DecimalMin("0.00")BigDecimal amount,@NotBlank String method,@NotBlank String status){}
}
