package lk.sliit.nutricare.access;
import jakarta.servlet.*;import jakarta.servlet.http.*;import java.io.IOException;import java.util.List;import org.springframework.beans.factory.annotation.Value;import org.springframework.context.annotation.*;import org.springframework.http.HttpHeaders;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.config.annotation.method.configuration.EnableMethodSecurity;import org.springframework.security.config.annotation.web.builders.HttpSecurity;import org.springframework.security.config.http.SessionCreationPolicy;import org.springframework.security.core.authority.SimpleGrantedAuthority;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.security.web.SecurityFilterChain;import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;import org.springframework.stereotype.Component;import org.springframework.web.cors.*;import org.springframework.web.filter.OncePerRequestFilter;
@Configuration @EnableMethodSecurity public class SecurityConfig{
 @Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}
 @Bean CorsConfigurationSource cors(@Value("${nutricare.web-origin:http://localhost:5173}")String origin){CorsConfiguration c=new CorsConfiguration();c.setAllowedOrigins(List.of(origin));c.setAllowedMethods(List.of("GET","POST","PUT","PATCH","DELETE","OPTIONS"));c.setAllowedHeaders(List.of("*"));UrlBasedCorsConfigurationSource s=new UrlBasedCorsConfigurationSource();s.registerCorsConfiguration("/**",c);return s;}
 @Bean SecurityFilterChain chain(HttpSecurity http,BearerFilter bearer)throws Exception{return http.csrf(c->c.disable()).cors(c->{}).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/v1/auth/**","/api/v1/demo/**","/error").permitAll().anyRequest().authenticated()).addFilterBefore(bearer,UsernamePasswordAuthenticationFilter.class).build();}
}
@Component class BearerFilter extends OncePerRequestFilter{private final TokenService tokens;BearerFilter(TokenService tokens){this.tokens=tokens;}protected void doFilterInternal(HttpServletRequest req,HttpServletResponse res,FilterChain chain)throws ServletException,IOException{String h=req.getHeader(HttpHeaders.AUTHORIZATION);if(h!=null&&h.startsWith("Bearer ")){try{var c=tokens.verify(h.substring(7));SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(c.userId(),null,List.of(new SimpleGrantedAuthority("ROLE_"+c.role()))));}catch(RuntimeException ignored){}}chain.doFilter(req,res);}}

