package lk.sliit.nutricare.access;
import com.fasterxml.jackson.databind.ObjectMapper;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.Instant;import java.util.*;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;
@Service public class TokenService{
 private final byte[] secret;private final long hours;private final ObjectMapper mapper=new ObjectMapper();
 public TokenService(@Value("${nutricare.jwt-secret}")String secret,@Value("${nutricare.jwt-hours:8}")long hours){this.secret=secret.getBytes(StandardCharsets.UTF_8);this.hours=hours;}
 public String issue(UserAccount user){try{String h=encode("{\"alg\":\"HS256\",\"typ\":\"JWT\"}");String p=encode(mapper.writeValueAsBytes(Map.of("sub",user.getId().toString(),"email",user.getEmail(),"role",user.getRole(),"exp",Instant.now().plusSeconds(hours*3600).getEpochSecond())));return h+"."+p+"."+sign(h+"."+p);}catch(Exception e){throw new IllegalStateException("Could not issue token");}}
 public Claims verify(String token){try{String[]p=token.split("\\.");if(p.length!=3||!MessageDigest.isEqual(sign(p[0]+"."+p[1]).getBytes(),p[2].getBytes()))throw new IllegalArgumentException("Invalid token");Map<?,?>m=mapper.readValue(Base64.getUrlDecoder().decode(p[1]),Map.class);long exp=((Number)m.get("exp")).longValue();if(exp<Instant.now().getEpochSecond())throw new IllegalArgumentException("Token expired");return new Claims(UUID.fromString((String)m.get("sub")),(String)m.get("email"),(String)m.get("role"));}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalArgumentException("Invalid token");}}
 private String sign(String value)throws Exception{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(secret,"HmacSHA256"));return encode(mac.doFinal(value.getBytes(StandardCharsets.UTF_8)));}private String encode(String s){return encode(s.getBytes(StandardCharsets.UTF_8));}private String encode(byte[]b){return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}public record Claims(UUID userId,String email,String role){}
}
