import { useState } from "react";
import { CalendarCheck, CircleDollarSign, Clock3, Plus } from "lucide-react";

const slots = ["09:00", "10:30", "11:45", "14:00", "15:30"];
export function AppointmentBillingFeature() {
  const [chosen, setChosen] = useState("10:30");
  const [bookings, setBookings] = useState([{ patient: "Amal Perera", practitioner: "Ms. Ishara Jayasinghe", time: "10:30", status: "Confirmed", amount: "LKR 3,500" }]);
  const [saved, setSaved] = useState(false);
  function book(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBookings((rows) => [...rows, { patient: String(data.get("patient")), practitioner: String(data.get("practitioner")), time: chosen, status: "Held · 10 min", amount: "LKR 3,500" }]); setSaved(true); }
  return <div className="stack-xl"><div className="page-heading"><div><span className="eyebrow">Module 02 · IT25103681</span><h1>Appointments & billing</h1><p>Conflict-free scheduling with invoices and safe simulated payments.</p></div><button className="primary" onClick={() => document.getElementById("booking-form")?.scrollIntoView({behavior:"smooth"})}><Plus size={17}/> New booking</button></div>
    <section className="metric-row"><article className="metric"><span>Available today</span><strong>8 slots</strong></article><article className="metric"><span>Confirmed</span><strong>12</strong></article><article className="metric"><span>Outstanding</span><strong>LKR 7,000</strong></article></section>
    <div className="feature-grid"><section className="panel"><div className="panel-title"><div><span className="eyebrow">Thursday 03 Sep</span><h2>Available consultation times</h2></div><CalendarCheck size={20}/></div><div className="chip-row">{slots.map((slot)=><button key={slot} className={chosen===slot?"chip active":"chip"} onClick={()=>setChosen(slot)}><Clock3 size={12}/> {slot}</button>)}</div><div className="list" style={{marginTop:18}}>{bookings.map((booking,i)=><div className="list-item" key={`${booking.patient}-${i}`}><span className="avatar">{booking.patient[0]}</span><span className="grow"><strong>{booking.patient}</strong><small>{booking.practitioner} · {booking.time}</small></span><span><span className={booking.status.startsWith("Confirmed")?"status confirmed":"status pending"}>{booking.status}</span><small style={{display:"block",marginTop:5}}>{booking.amount}</small></span></div>)}</div></section>
    <section className="panel" id="booking-form"><div className="panel-title"><div><span className="eyebrow">Reserve & invoice</span><h2>Create appointment</h2></div><CircleDollarSign size={20}/></div><form className="form-grid" onSubmit={book}><div className="field full"><label htmlFor="patient">Patient</label><input id="patient" name="patient" required placeholder="Patient name"/></div><div className="field full"><label htmlFor="practitioner">Practitioner</label><select id="practitioner" name="practitioner"><option>Ms. Ishara Jayasinghe</option><option>Dr. Chamara Fernando</option></select></div><div className="field"><label>Selected time</label><input value={chosen} readOnly/></div><div className="field"><label htmlFor="payment">Payment status</label><select id="payment" name="payment"><option>Pending</option><option>Paid</option><option>Partially paid</option></select></div><button className="primary field full" type="submit">Hold slot & generate invoice</button></form>{saved&&<div className="success-note">Slot held for 10 minutes and demo invoice generated. No card details were stored.</div>}</section></div>
  </div>;
}

